# comments

#Target : dependency
#<TAB>Command

PROJECT_NAME =all.exe
SRC = main.c\
src\Monthly_Financial_cal.c

INC= inc

$(PROJECT_NAME): $(SRC)
	gcc -I $(INC) $(SRC) -o all.exe

run :all.exe
	all.exe	


clean:
	del/q *.exe


# gcc main.c test_complex_calculator.c  -o all.exe























